# fly.toml app configuration file generated for pretty-gpx on 2024-09-10T19:57:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pretty-gpx'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2
