name: PR Conventional Commit Validation

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@1.3.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'
          custom_labels: '{"feat": "enhancement", "fix": "bug", "docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "revert": "revert"}'


